### ISSUE TITLE
[REQUEST] Adapt status pop-up to dark mode

### ISSUE THREAD

**Issue by FreunderNacht** [kantlivelong/OctoPrint-UPS#1]
Hi,
very nice plugin for the OctoPrint.

Thanks

I only noticed that it is very difficult to read the status popup in Darktmode:

![image](https://user-images.githubusercontent.com/69077006/131229402-c1fe6b3d-15c2-4446-834f-9fb36711f6e8.png)

Could this still be adjusted?

Thanks a lot
FreundderNacht

**Comment by kantlivelong** [comment]
You'll want to make that request to whichever theming plugin you are using as it looks like it's not properly handling popovers.

**Comment by kantlivelong** [comment]
https://github.com/Birkbjo/OctoPrint-Themeify/issues/107

**Comment by LazeMSS** [comment]
Use UI customizer 🤣
