### ISSUE TITLE
Font color in pop-up window

### ISSUE THREAD

**Issue by ekorolkov** [kantlivelong/OctoPrint-UPS#11]
Hi!
Nice plugin!

Is it possible to fix font color in pop-up window when Themeify Discorded theme is activated? Now it is displayed like this
![UPS](https://user-images.githubusercontent.com/20777266/142735929-a6aeee59-8ffe-4231-ab9e-45774945f7b2.png)

**Comment by kantlivelong** [comment]
Dupe #1 

Issue is with Themeify.

**Comment by kantlivelong** [comment]
https://github.com/Birkbjo/OctoPrint-Themeify/issues/107
