### ISSUE TITLE
[REQUEST] USB Connection to UPS instead of only LAN

### ISSUE THREAD

**Issue by TomKamin1** [kantlivelong/OctoPrint-UPS#7]
Hey !

I am using a Eaton 5S 700, which is connected to via the USB port on it. Your NUT config however does seem to only be through LAN, meaning i cannot connect to the UPS in any way. Is it possible to add a option to use a USB port for the connection, besides the built-in network ? NUT should be fully capable of doing this if i remember correctly.

Thanks ! 

Tom

**Comment by kantlivelong** [comment]
The plugin only communicates with NUT. You need to config NUT yourself then point then plugin to it.
